let allFruits=[
    {
        id:1,
        name:"mango",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukm/ukmam/ukmammo027.mp3"
    },
    {
        id:2,
        name:"apple",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukapp/ukappen014.mp3",
    },
    {
        id:3,
        name:"pineapple",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukp/ukpil/ukpilot019.mp3",
    },
    {
        id:4,
        name:"orange",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uko/ukora/ukorang001.mp3",
    },
    {
        id:5,
        name:"guava",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukg/ukgua/ukguate003.mp3",
    },
    {
        id:6,
        name:"grape",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukg/ukgra/ukgranu004.mp3",
    },
    {
        id:7,
        name:"watermealon",
        source:"https://dictionary.cambridge.org/media/english/us_pron/w/wat/water/watermelon.mp3",
    },

];